[app]
name = "EMF Cave"
category = "Games"

[entry]
class = "EMFCave"

[metadata]
author = "pikesley"
license = "MIT"
url = "https://www.github.com/pikesley/tildagon-emf-cave"
description = "A reimplementation of an ancient Palm Pilot game, SFCave"
version = "0.0.4"
